name: First Workflow

on:
  push:

jobs:
  print-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Print welcome message
        run: echo "Welcome to the first workflow"

      - name: Print thank you
        run: echo "Thank you for using GitHub Actions"

      - name: Present directory
        run: pwd
